### ISSUE TITLE
Pierre Salvy, greatest coder in the world

### ISSUE THREAD

**Issue by zakandrewking** [SBRG/ome#14]
@P0N3Y: I know you have an elegant and beautiful function for extracting a COBRA model from the OME database. Do you think you could submit a PR for that function? We could run it by @jlerman44 too...

Thanks! I hope you guys are doing well up there.

-Zak

**Comment by P0N3Y** [comment]
@zakandrewking I really hope we are the only ones on this thread ahaha. As I told you, I'll submit this to the IP guys so that they give me the thumbs up to give it to you. 
I hope you guys are doing well down there :)

-Pierre

**Comment by zakandrewking** [comment]
OK. Thanks Pierre. sounds good.

**Comment by P0N3Y** [comment]
Hi Zak,

Got the thumbs up for sharing this code. I will work a little on it so I can ensure its compatibility with the master branch. Will submit a PR soon, hopefully before I leave :)

**Comment by zakandrewking** [comment]
Excellent! Can you submit the PR against the branch called 'bigg'? Don't worry about compatibility too much—we're still changing a lot of things on that branch. But, this way, i can get your code integrated and back in the master as we finish up. 




Best,

Zak



—

**Comment by P0N3Y** [comment]
Will do.

**Comment by P0N3Y** [comment]
Concerning compatibility, I'll do minor modifcations to my code just to remove some useless stuff for you then, and I can help you integrate it if you want.

Are you also interested in the GPR -> reverse Polish notation -> Tree algorithm ? (note: this needs a supplementary table).

**Comment by zakandrewking** [comment]
Definitely! We'd love to have that. 



—

**Comment by P0N3Y** [comment]
Okay, I'll join you the code for it.

**Comment by P0N3Y** [comment]
Also what about domain handling and group filtering ? my actual version allows you to filter in and out reaction groups. Do you want that ? (this also needs you to have reaction groups tables, but that's pretty straightforward)

**Comment by zakandrewking** [comment]
No, we won't be using those features. So don't worry about them. 



—

**Comment by P0N3Y** [comment]
I will post 3 files: 
* The pull_model script that handles the heavy lifting
* The gpr_rpn_tree file that does the eval/compilation of GPRs
* browsing_tools which is a bunch of functions for interacting with the database
Since you are rewriting a lot of stuff, as agreed, you might have to go through the main script (pull_model) to glue everything together.
I will submit the PR as @Amyris.
